name: Update README ‚≠ê
on:
  push:
    branches:
      - main
  schedule:
    - cron: "00 */6 * 12 *"  # Every 6 hours at x:01
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2786570
          leaderboardId: 2786570
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update README stars